ALTER TABLE tasks DROP COLUMN IF EXISTS priority;
ALTER TABLE tasks DROP COLUMN IF EXISTS due_date;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS time_estimate TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS assignee TEXT;